title: "Naol's Quest"  
author: "Naol Berhanu"  
description: "Exploring everything tech—from coding and cybersecurity to Android dev and software testing. A blog for curious minds and relentless learners."  

# Email / Social media usernames used by the minima theme:
email: "naolberhanu100@gmail.com"  
telegram_username: "@isnaaol"  
Resume:          /resume
#########################################################################################  
######### Nothing below needs to be changed (unless you know what you're doing) #########  
#########################################################################################  
theme: "minima"  

# rss: rss  

# kramdown:  
#   syntax_highlighter_opts:  
#     disable: true  

plugins:  
  - jekyll-feed  
  - jekyll-sitemap  

titles_from_headings:  
  strip_title: true  
  collections: true  

defaults:  
  - scope:  
      path: ""  
      type: post  
    values:  
      tags: Tech  
